url: https://nathanwebsterdotme.github.io/bpa
baseurl: ""

# Site settings
title: BPA - British Passing Academy
email: tkharchi@gmail.com
description: "BPA - British Passing Academy"


# Team names, titles and social links
people:
- name: Tom Kharchi
  pic: tom_kharchi
  position: Founder & Head Coach
  social:
    - title: twitter
      url: https://twitter.com/tkharchi

- name: Coach 2
  pic: 2
  position: Coach
  social:
    - title: twitter
      url: #

- name: Coach 3
  pic: 3
  position: Coach
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/BritishPassingAcademy/
    icon: fa-facebook-square
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Sheffield Hallam University Sports Park
  - line: Bawtry Rd, Sheffield S9 1UA

# Build settings
markdown: kramdown
permalink: pretty
categories: ['upcoming', 'past']
