url: https://nathanwebsterdotme.github.io/bpa
baseurl: ""

# Site settings
title: BPA - British Passing Academy
email: tkharchi@gmail.com
description: "BPA - British Passing Academy"


# Team names, titles and social links
people:
- name: Tom Kharchi
  pic: tom_kharchi
  position: Founder & Head Coach
  social:
    - title: twitter
      url: https://twitter.com/tkharchi

- name: Zach Shaw
  pic: zach_shaw
  position: Guest Coach - Europes Elite
  social:
    - title: facebook
      url: https://www.facebook.com/events/413634979074036/

- name: Adam Behrands
  pic: adam_behrands
  position: Guest Coach - IMG Academy
  social:
    - title: facebook
      url: https://www.facebook.com/events/208674916396224/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/BritishPassingAcademy/
    icon: fa-facebook-square
  - title: twitter
    url: https://twitter.com/tkharchi
    icon: fa-twitter-square
  - title: instagram
    url: https://www.instagram.com/tkharchi/
    icon: fa-instagram

# Postal address (add as many lines as necessary)
address:
  - line: Sheffield Hallam University Sports Park
  - line: Bawtry Rd, Sheffield S9 1UA

# Build settings
markdown: kramdown
permalink: pretty
categories: ['upcoming', 'past']
